/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kim' at '2016/11/29 下午 3:39' with Gradle 3.2.1
 *
 * @author kim, @date 2016/11/29 下午 3:39
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
